In [2]:
import numpy as np
import pandas as pd


In [3]:
A = [1,2,3,4,5,6]
B = [13,21,24]

A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 24]


In [4]:
#id = np.array[(1,0,0),(0,1,0),(0,0,1)]
id1 = np.array([[1,0,0],[0,1,0], [0,0,1]])
#id2 = eye(3)
print (id1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
fuel_data = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')
fuel_data.head(15)

record_id  ...  fuel_cost_per_mmbtu
0    f1_fuel_1994_12_1_0_7  ...                1.121
1   f1_fuel_1994_12_1_0_10  ...                1.120
2    f1_fuel_1994_12_2_0_1  ...                1.650
3    f1_fuel_1994_12_2_0_7  ...                1.970
4   f1_fuel_1994_12_2_0_10  ...                2.570
5   f1_fuel_1994_12_2_0_13  ...                1.850
6    f1_fuel_1994_12_2_1_1  ...                0.450
7   f1_fuel_1994_12_2_1_10  ...                2.360
8   f1_fuel_1994_12_2_2_10  ...                1.400
9    f1_fuel_1994_12_4_0_1  ...                1.278
10   f1_fuel_1994_12_4_0_2  ...               13.900
11   f1_fuel_1994_12_4_0_4  ...                1.280
12   f1_fuel_1994_12_4_0_5  ...                1.900
13   f1_fuel_1994_12_6_0_1  ...                1.208
14   f1_fuel_1994_12_6_0_2  ...                5.469

[15 rows x 11 columns]

In [6]:
fuel_data['fuel_type_code_pudl'].unique()

array(['coal', 'gas', 'nuclear', 'oil', 'waste', 'other'], dtype=object)

In [7]:
#fuel_data['fuel_type_code_pudl']
fuel_data['fuel_cost_per_unit_burned']

0        18.59
1        18.58
2        39.72
3        47.21
4         2.77
         ...  
29518     4.78
29519     3.65
29520     4.77
29521     3.06
29522     0.00
Name: fuel_cost_per_unit_burned, Length: 29523, dtype: float64

In [8]:
fuel_code = fuel_data.groupby('fuel_type_code_pudl')
print (fuel_code['fuel_cost_per_unit_burned'].agg(np.mean))
                              

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64


In [9]:
unit = fuel_data['fuel_mmbtu_per_unit']
unit.head()
print(unit.std(),unit.quantile(q=0.75))


10.600220307806886 17.006


In [10]:
qty_burned = fuel_data['fuel_qty_burned']
print(qty_burned.skew(),qty_burned.kurt())


15.851495469109503 651.3694501337732


In [11]:

check_null = fuel_data.isnull().sum()
print(check_null)
print((180/29523) *100)


record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
0.609694136774718


In [12]:
fuel_data.corr()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
utility_id_ferc1                      1.000000  ...             0.006122
report_year                           0.093323  ...             0.010261
fuel_qty_burned                      -0.057447  ...            -0.001896
fuel_mmbtu_per_unit                  -0.066946  ...            -0.005884
fuel_cost_per_unit_burned            -0.037863  ...            -0.000437
fuel_cost_per_unit_delivered         -0.016414  ...            -0.000109
fuel_cost_per_mmbtu                   0.006122  ...             1.000000

[7 rows x 7 columns]

In [60]:
#fuel_code = fuel_data.groupby('fuel_type_code_pudl')
#fuel_code.head()
#fuel_data['report_year'].unique()


data = fuel_data[['report_year','fuel_type_code_pudl','fuel_cost_per_unit_burned']]
data.head()
grouped = data.groupby(['report_year','fuel_type_code_pudl']).pct_change()
pd.options.display.max_rows = 4000
print(grouped)

       fuel_cost_per_unit_burned
0                            NaN
1                      -0.000538
2                       1.137783
3                       0.188570
4                            NaN
...                          ...
29518                  -0.426170
29519                  -0.236402
29520                   0.306849
29521                  -0.776479
29522                  -1.000000

[29523 rows x 1 columns]


In [55]:
data1 = fuel_data[['report_year','fuel_cost_per_unit_delivered']]
data1.head()
group1  = data1.groupby(['report_year']).agg({'fuel_cost_per_unit_delivered': 'mean'})
print(group1)

             fuel_cost_per_unit_delivered
report_year                              
1994                            63.636060
1995                            32.735269
1996                          9196.705948
1997                         11140.197239
1998                           287.154420
1999                            25.551627
2000                           985.362877
2001                            60.050396
2002                            47.594361
2003                            55.663493
2004                           139.524275
2005                            41.438184
2006                            38.657484
2007                            43.325023
2008                            58.588197
2009                           652.694163
2010                            91.862105
2011                            59.774667
2012                            60.994502
2013                           172.307591
2014                           192.737183
2015                           326